### ISSUE TITLE
Extra Semicolon at Line 210

### ISSUE THREAD

**Issue by Laraveldeep** [Wikiki/bulma-calendar#126] opened 2018-12-20 18:47 UTC
There is an extra semicolon at line 210 of `dist/css/bulma-calendar.sass`

This issue was filed on 

https://github.com/laravel-frontend-presets/bulma/issues/22

**Comment by kobadg** [comment] 2019-01-08 18:51
@Wikiki Please open back up.

Issue still persists today. (Removal of the ; fixes the issue.)

**Comment by TinoN** [comment] 2019-01-09 04:50
@Wikiki Please open back up.

Issue still persists today. (Removal of the ; fixes the issue.)

**Comment by TinoN** [comment] 2019-01-09 04:51
Issue still persists today. (Removal of the ; fixes the issue.)

**Comment by Wikiki** [comment] 2019-01-09 08:44
Hi,

I reopen the issue but I don't see the semicolon into the files of the repository (neither in dist/css or src/sass).

**Comment by TinoN** [comment] 2019-01-09 09:43
Well unfortunately I can't reproduce the error.
After uninstalling bulma-calendar and reinstalling via npm, I am not seeing the line/semicolon anymore that caused the error a couple of hours ago :(

**Comment by kobadg** [comment] 2019-01-09 16:24
I'm seeing that is was removed in the bit 9 days ago? But yet when I pulled it yesterday, it still had it... Maybe NPM wasn't updated to the new version yet?

**Comment by jhoff** [comment] 2019-01-21 22:49
This is still an issue because while it's [fixed in the master branch](https://github.com/Wikiki/bulma-calendar/commit/4f511cb6cd3f5a540a9d6ca4d1238b7cb4e36dde#diff-19dd2b30eb1be97bb82a0eb6f9788ae4L210), the most recent release ( v5.0.2 ) still has the bug. Whenever they do a new release the issue should go away for downstream dependencies.

**Comment by Wikiki** [comment] 2019-01-22 07:31
I'll update the npm version tonight

**Comment by CreativeBulma** [comment] 2019-01-23 20:49
Hi @jhoff,

last version is not 5.0.2 but 5.0.5 (released 24 days ago) please try with it.

**Comment by jhoff** [comment] 2019-01-23 20:52
The latest version according to https://github.com/Wikiki/bulma-calendar/releases/ is 5.0.2

https://github.com/Wikiki/bulma-calendar/releases/tag/v5.0.5 returns a 404?

**Comment by jhoff** [comment] 2019-01-23 20:55
https://www.npmjs.com/package/bulma-calendar/v/5.0.5 looks like a thing I guess...

**Comment by Wikiki** [comment] 2019-01-23 20:55
Hi,

latest on npmjs is 5.0.5. I've forgot to release it on Github. It's done now.
Sorry for the inconvenience.

**Closed** 2019-01-25 13:38 UTC
Labels: bug
