### ISSUE TITLE
dateFormat DD/MM/YYYY second click on textbox

### ISSUE THREAD

**Issue by jirisarri10** [Wikiki/bulma-calendar#108] opened 2018-10-06 17:51 UTC
Hello:
Need help regarding the DD / MM / YYYY date format. When I click on the calendar, selecting a date the result shown in the text box is correct. However, when I click on the DD / MM / YYYY date displayed in the text box, the calendar navigates in MM / DD / YYYY format. For example, if the first time clicked on a date 02/10/2018 (October 2), when, subsequently, I click on the text box the calendar shows 10/02/2018 (February 10). I would like to know if I am doing something wrong in the configuration or it is due to an error.
I love this extension.
Thank you very much.
Sincerely,
Javier Irisarri (jirisarri10@gmail.com)

**Comment by Wikiki** [comment] 2018-10-08 12:01
Hi @jirisarri10,

Based on your post you don't do anything wrong. It should be a bug. I'll have a look on it.

**Comment by jirisarri10** [comment] 2018-10-08 13:35
Very friendly. I apreciate your quick response. Thank very much.

El 8 oct. 2018 14:01, "Wikiki" <notifications@github.com> escribió:

Hi @jirisarri10 <https://github.com/jirisarri10>,

Based on your post you don't do anything wrong. It should be a bug. I'll
have a look on it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Wikiki/bulma-calendar/issues/108#issuecomment-427807224>,
or mute the thread

**Comment by marovargovcik** [comment] 2018-10-16 06:38
Hey, any updates on this?

I played with calendar a bit and discovered that "DD. MMM YYYY" and "DD. MMMM YYYY" formats work just fine. These formats represents months with words instead of number - Oct. and October.
"M" and "MM" in formats are causing this behavior.

**Comment by Wikiki** [comment] 2018-10-16 14:02
Hi,

I'm working on it.

**Comment by marovargovcik** [comment] 2018-10-16 14:37
https://codepen.io/anon/pen/aREEdx?editors=1000#0

It's also behaving same formatDate: "DD/MM/YYYY".

**Comment by Wikiki** [comment] 2018-10-16 14:39
I think I've found it. Please try with last version committed

**Comment by marovargovcik** [comment] 2018-10-16 15:01
https://codepen.io/anon/pen/aREEdx?editors=1000#0

I see no difference. Still bugging.

I also discovered another bug when using "DD.MM.YYYY". 

Steps to reproduce -
1. Click calendar (isRange: true, dateFormat: ""DD.MM.YYYY")
2. Select begin date (16 Oct 2018)
3. Select end date earlier (12 Oct 2018)
4. Repeat this once or twice
5. Calendar is no longer working and there is error in console saying:
Uncaught Error: The start of the range cannot be after the end of the range

**Comment by Wikiki** [comment] 2018-10-16 15:32
@marovargovcik  thanks for your help.... I'll try to figure it out

**Comment by Wikiki** [comment] 2018-10-16 16:30
Sorry but even with your codepen I can't reproduce both errors.
The dateformat is well applied : D.M.YYYY ; M.D.YYYY ; MM.DD.YYYY ; DD.MM.YYYY

And range selection does not break :-(
It's difficult to help without having the issue on my side

**Comment by poojaagarwal1009** [comment] 2018-10-17 03:05
I'm Also facing the same issue along with that i'm also facing another issue.
Inside my componentDidMout() method attching the bulmaCalendar with options as follow

const calendars = bulmaCalendar.attach('[type="date"]', {
      dateFormat: 'DD/MM/YYYY',
      clearButton: false
    });

Now in the text box if i manually enter a date (assuming DD/MM/YYYY) and open the calendar it displays the date in the MM/DD/YYYY format if it can, else either shows previously selected value or blank in the language section.
ex: 09/10/2018- should show 9th october but shows 10 september
![image](https://user-images.githubusercontent.com/14246787/47059477-3f1fe080-d215-11e8-8e31-a84c0845a208.png)
ex: 18/10/2018 - should show 18th october but display old value or black if there is no previous value
![image](https://user-images.githubusercontent.com/14246787/47059542-85753f80-d215-11e8-83e8-479b0b510a48.png)

![image](https://user-images.githubusercontent.com/14246787/47059580-afc6fd00-d215-11e8-948f-32938e98814b.png)


Cheers!

**Comment by Wikiki** [comment] 2018-10-17 10:34
The library used for date manipulation : date-fns doesn't support format in parse function
I'll run some tests with the incoming v2 version but I'll not be able to fix this issue until this version is released unless I found a workaround to parse the date manually.

**Comment by lucas-warren** [comment] 2018-10-17 16:10
I had the same issue and it seem to be fixed

thanks @Wikiki.

**Closed** 2018-10-17 19:02 UTC
Labels: bug

**Comment by poojaagarwal1009** [comment] 2018-10-19 23:41
Yes it seem to be fixed.
Awesome!
Thanks

**Comment by JacksonJeans** [comment] 2019-07-01 13:28
I have the same bug, of course I use the latest version. I also use the DD/MM/YYYY format and when debugging I noticed that the bug only applies if you select a tag below 13.

**Comment by JacksonJeans** [comment] 2019-07-17 11:56
Here is a temporary fix for those who have the same problem with the DD/MM/YYYY format.

The fix resets the event and returns false at the end so that bulma calendar does not open the wrapper and triggers the error. We now open it ourselves by toggling the "is-active" CSS class.

Now the wrapper opens and executes the selected date on click events and returns it in the set DD/MM/YYYY format.


` $('input.datetimepicker-dummy-input').click(function(event){
    console.log('Datetime Picker wurde aufgerufen');   
    event.preventDefault();
    var datetimepicker =  $(this).parent().parent().parent().children('.datetimepicker-wrapper').children('.datetimepicker');
    $(datetimepicker).toggleClass('is-active');
    return false;
  });`
